runtime: nodejs10

instance_class: F2

default_expiration: "1h"

handlers:
  - url: /_nuxt
    static_dir: .nuxt/dist/client
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt)$
    secure: always

  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 1

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
